import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import ts from 'typescript';
const values = new Map();
globalThis.localStorage = { getItem: k => values.get(k) ?? null, setItem: (k,v) => values.set(k,v), removeItem: k => values.delete(k) };
globalThis.window = new EventTarget();
const source = readFileSync('src/services/authService.ts', 'utf8').replace('(import.meta as any).env?.VITE_API_URL', 'undefined');
const code = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2020 } }).outputText;
const api = await import('data:text/javascript;base64,' + Buffer.from(code).toString('base64'));
let calls = [];
let reply = { success: true };
let status = 200;
globalThis.fetch = async (url, opts) => { calls.push({url, ...opts}); return new Response(JSON.stringify(reply), {status}); };
reply = {success:true, token:'token', user:{username:'aluno',role:'STUDENT'}};
assert.equal((await api.authenticateUser(' ALUNO ', ' senha com espaços ')).ok, true);
assert.equal(JSON.parse(calls.at(-1).body).password, ' senha com espaços ');
reply = {success:false,message:'Duplicado'}; status=409;
assert.deepEqual(await api.registerNewUser({name:'Aluno',email:'a@b.com',cpf:'123',username:'aluno',password:'abcdefgh'}), {success:false,message:'Duplicado'});
assert.equal(calls.at(-1).method, 'POST');
status=403; reply={success:false,message:'Proibido'};
const before=calls.length;
await assert.rejects(api.updateUserStatus('1','APPROVED'), /Proibido/);
assert.equal(calls.length,before+1);
status=200; reply={success:true,users:[{id:'1'}]};
assert.equal((await api.getStoredUsers()).length,1);
reply={success:true,users:[]};
assert.equal((await api.getStoredUsers()).length,0);
assert.equal(api.exportUsersJson(),'[]');
status=401; reply={success:false,message:'Expirada'};
await assert.rejects(api.getSessionUser(),/Expirada/);
assert.equal(values.has('gaf_auth_token'),false);
assert.equal(api.importUsersJson('[{"role":"ADMIN"}]').success,false);
console.log('OK: senha preservada, duplicidade, falha sem fallback, lista autoritativa, sessão expirada e importação sem concessão de acesso.');
