import { ParameterMap } from '../types/cfw500';

export const INITIAL_PARAMETERS: ParameterMap = {
  // ==========================================
  // GRUPO 1: MONITORAMENTO (P0000 - P0099)
  // ==========================================
  P0000: {
    code: 'P0000',
    description: 'Acesso aos Parâmetros (Senha de Desbloqueio = 5)',
    min: 0,
    max: 9999,
    step: 1,
    defaultValue: 5,
    currentValue: 5,
    unit: '',
  },
  P0001: {
    code: 'P0001',
    description: 'Velocidade do Motor',
    min: 0,
    max: 18000,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: 'rpm',
    readOnly: true,
  },
  P0002: {
    code: 'P0002',
    description: 'Frequência de Saída do Inversor',
    min: 0,
    max: 300.0,
    step: 0.1,
    defaultValue: 0.0,
    currentValue: 0.0,
    unit: 'Hz',
    readOnly: true,
  },
  P0003: {
    code: 'P0003',
    description: 'Corrente de Saída no Motor',
    min: 0,
    max: 100.0,
    step: 0.1,
    defaultValue: 0.0,
    currentValue: 0.0,
    unit: 'A',
    readOnly: true,
  },
  P0004: {
    code: 'P0004',
    description: 'Tensão do Barramento / Link CC',
    min: 0,
    max: 800,
    step: 1,
    defaultValue: 310,
    currentValue: 310,
    unit: 'V',
    readOnly: true,
  },
  P0005: {
    code: 'P0005',
    description: 'Frequência da Referência de Velocidade',
    min: 0,
    max: 300.0,
    step: 0.1,
    defaultValue: 60.0,
    currentValue: 60.0,
    unit: 'Hz',
    readOnly: true,
  },
  P0006: {
    code: 'P0006',
    description: 'Estado Atual do Inversor (0=Ready, 1=Run, 2=Fault)',
    min: 0,
    max: 10,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
    readOnly: true,
  },
  P0007: {
    code: 'P0007',
    description: 'Tensão de Saída para o Motor',
    min: 0,
    max: 500,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: 'V',
    readOnly: true,
  },
  P0008: {
    code: 'P0008',
    description: 'Fator de Potência da Carga (cos phi)',
    min: 0,
    max: 1.0,
    step: 0.01,
    defaultValue: 0.82,
    currentValue: 0.82,
    unit: '',
    readOnly: true,
  },
  P0009: {
    code: 'P0009',
    description: 'Torque de Saída Estimado',
    min: -200.0,
    max: 200.0,
    step: 0.1,
    defaultValue: 0.0,
    currentValue: 0.0,
    unit: '%',
    readOnly: true,
  },
  P0010: {
    code: 'P0010',
    description: 'Potência de Saída Ativa',
    min: 0,
    max: 100.0,
    step: 0.1,
    defaultValue: 0.0,
    currentValue: 0.0,
    unit: 'kW',
    readOnly: true,
  },
  P0011: {
    code: 'P0011',
    description: 'Fator de Sobrecarga do Inversor Ixt',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '%',
    readOnly: true,
  },
  P0012: {
    code: 'P0012',
    description: 'Status das Entradas Digitais (DI1 a DI4)',
    min: 0,
    max: 15,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
    readOnly: true,
  },
  P0013: {
    code: 'P0013',
    description: 'Status das Saídas Digitais a Relé (DO1/DO2)',
    min: 0,
    max: 7,
    step: 1,
    defaultValue: 1,
    currentValue: 1,
    unit: '',
    readOnly: true,
  },
  P0014: {
    code: 'P0014',
    description: 'Leitura do Sinal da Entrada Analógica AI1',
    min: 0,
    max: 100.0,
    step: 0.1,
    defaultValue: 0.0,
    currentValue: 0.0,
    unit: '%',
    readOnly: true,
  },
  P0018: {
    code: 'P0018',
    description: 'Valor da Entrada Analógica AI1 em Tensão',
    min: 0,
    max: 10.0,
    step: 0.1,
    defaultValue: 0.0,
    currentValue: 0.0,
    unit: 'V',
    readOnly: true,
  },
  P0023: {
    code: 'P0023',
    description: 'Versão do Software / Firmware',
    min: 0,
    max: 99.99,
    step: 0.01,
    defaultValue: 3.20,
    currentValue: 3.20,
    unit: '',
    readOnly: true,
  },
  P0030: {
    code: 'P0030',
    description: 'Temperatura dos Módulos IGBT / Dissipador',
    min: 0,
    max: 150,
    step: 1,
    defaultValue: 38,
    currentValue: 38,
    unit: '°C',
    readOnly: true,
  },
  P0037: {
    code: 'P0037',
    description: 'Fator de Sobrecarga do Motor Ixt',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '%',
    readOnly: true,
  },
  P0050: {
    code: 'P0050',
    description: 'Última Falha Ocorrida (Histórico de Erros)',
    min: 0,
    max: 999,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
    readOnly: true,
  },

  // ==========================================
  // GRUPO 2: RAMPAS E LIMITES (P0100 - P0149)
  // ==========================================
  P0100: {
    code: 'P0100',
    description: 'Tempo da Rampa de Aceleração 1',
    min: 0.1,
    max: 999.0,
    step: 0.1,
    defaultValue: 5.0,
    currentValue: 5.0,
    unit: 's',
  },
  P0101: {
    code: 'P0101',
    description: 'Tempo da Rampa de Desaceleração 1',
    min: 0.1,
    max: 999.0,
    step: 0.1,
    defaultValue: 5.0,
    currentValue: 5.0,
    unit: 's',
  },
  P0102: {
    code: 'P0102',
    description: 'Tempo da Rampa de Aceleração 2',
    min: 0.1,
    max: 999.0,
    step: 0.1,
    defaultValue: 10.0,
    currentValue: 10.0,
    unit: 's',
  },
  P0103: {
    code: 'P0103',
    description: 'Tempo da Rampa de Desaceleração 2',
    min: 0.1,
    max: 999.0,
    step: 0.1,
    defaultValue: 10.0,
    currentValue: 10.0,
    unit: 's',
  },
  P0104: {
    code: 'P0104',
    description: 'Forma da Rampa (0=Linear, 1=Rampa S Curva Suave)',
    min: 0,
    max: 1,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0105: {
    code: 'P0105',
    description: 'Seleção da 2ª Rampa (0=1ª Rampa, 1=2ª Rampa, 2=Via DI)',
    min: 0,
    max: 2,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0120: {
    code: 'P0120',
    description: 'Referência de Frequência do Teclado (IHM)',
    min: 0.0,
    max: 300.0,
    step: 0.1,
    defaultValue: 60.0,
    currentValue: 60.0,
    unit: 'Hz',
  },
  P0121: {
    code: 'P0121',
    description: 'Frequência de Referência Manual / Backup',
    min: 0.0,
    max: 300.0,
    step: 0.1,
    defaultValue: 60.0,
    currentValue: 60.0,
    unit: 'Hz',
  },
  P0122: {
    code: 'P0122',
    description: 'Frequência da Função JOG (Pulso/Avanço Lento)',
    min: 0.0,
    max: 300.0,
    step: 0.1,
    defaultValue: 5.0,
    currentValue: 5.0,
    unit: 'Hz',
  },
  P0123: {
    code: 'P0123',
    description: 'Frequência de Aceleração JOG',
    min: 0.1,
    max: 999.0,
    step: 0.1,
    defaultValue: 5.0,
    currentValue: 5.0,
    unit: 's',
  },
  P0124: {
    code: 'P0124',
    description: 'Referência Multispeed 1 (DI=000)',
    min: 0.0,
    max: 300.0,
    step: 0.1,
    defaultValue: 5.0,
    currentValue: 5.0,
    unit: 'Hz',
  },
  P0125: {
    code: 'P0125',
    description: 'Referência Multispeed 2 (DI=001)',
    min: 0.0,
    max: 300.0,
    step: 0.1,
    defaultValue: 10.0,
    currentValue: 10.0,
    unit: 'Hz',
  },
  P0126: {
    code: 'P0126',
    description: 'Referência Multispeed 3 (DI=010)',
    min: 0.0,
    max: 300.0,
    step: 0.1,
    defaultValue: 20.0,
    currentValue: 20.0,
    unit: 'Hz',
  },
  P0127: {
    code: 'P0127',
    description: 'Referência Multispeed 4 (DI=011)',
    min: 0.0,
    max: 300.0,
    step: 0.1,
    defaultValue: 30.0,
    currentValue: 30.0,
    unit: 'Hz',
  },
  P0128: {
    code: 'P0128',
    description: 'Referência Multispeed 5 (DI=100)',
    min: 0.0,
    max: 300.0,
    step: 0.1,
    defaultValue: 40.0,
    currentValue: 40.0,
    unit: 'Hz',
  },
  P0129: {
    code: 'P0129',
    description: 'Referência Multispeed 6 (DI=101)',
    min: 0.0,
    max: 300.0,
    step: 0.1,
    defaultValue: 50.0,
    currentValue: 50.0,
    unit: 'Hz',
  },
  P0130: {
    code: 'P0130',
    description: 'Referência Multispeed 7 (DI=110)',
    min: 0.0,
    max: 300.0,
    step: 0.1,
    defaultValue: 55.0,
    currentValue: 55.0,
    unit: 'Hz',
  },
  P0131: {
    code: 'P0131',
    description: 'Referência Multispeed 8 (DI=111)',
    min: 0.0,
    max: 300.0,
    step: 0.1,
    defaultValue: 60.0,
    currentValue: 60.0,
    unit: 'Hz',
  },
  P0133: {
    code: 'P0133',
    description: 'Frequência Mínima de Operação',
    min: 0.0,
    max: 300.0,
    step: 0.1,
    defaultValue: 3.0,
    currentValue: 3.0,
    unit: 'Hz',
  },
  P0134: {
    code: 'P0134',
    description: 'Frequência Máxima de Operação',
    min: 0.0,
    max: 300.0,
    step: 0.1,
    defaultValue: 60.0,
    currentValue: 60.0,
    unit: 'Hz',
  },
  P0135: {
    code: 'P0135',
    description: 'Corrente Máxima de Saída (Limite de Sobrecarga)',
    min: 0.0,
    max: 30.0,
    step: 0.1,
    defaultValue: 9.0,
    currentValue: 9.0,
    unit: 'A',
  },
  P0136: {
    code: 'P0136',
    description: 'Boost / Compensação de Torque Manual (V/F)',
    min: 0.0,
    max: 30.0,
    step: 0.1,
    defaultValue: 5.0,
    currentValue: 5.0,
    unit: '%',
  },
  P0137: {
    code: 'P0137',
    description: 'Boost de Torque Automático (Compensação de Carga)',
    min: 0.0,
    max: 30.0,
    step: 0.1,
    defaultValue: 0.0,
    currentValue: 0.0,
    unit: '%',
  },
  P0138: {
    code: 'P0138',
    description: 'Compensação de Escorregamento do Motor',
    min: 0.0,
    max: 10.0,
    step: 0.1,
    defaultValue: 1.0,
    currentValue: 1.0,
    unit: '%',
  },
  P0139: {
    code: 'P0139',
    description: 'Frequência de Chaveamento PWM dos IGBTs',
    min: 2.5,
    max: 15.0,
    step: 0.5,
    defaultValue: 5.0,
    currentValue: 5.0,
    unit: 'kHz',
  },
  P0140: {
    code: 'P0140',
    description: 'Tipo de Frenagem / Parada (0=Rampa, 1=Por Inércia)',
    min: 0,
    max: 1,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0142: {
    code: 'P0142',
    description: 'Nível de Tensão de Frenagem CC',
    min: 0.0,
    max: 30.0,
    step: 0.1,
    defaultValue: 0.0,
    currentValue: 0.0,
    unit: '%',
  },
  P0143: {
    code: 'P0143',
    description: 'Tempo de Aplicação da Frenagem CC na Parada',
    min: 0.0,
    max: 15.0,
    step: 0.1,
    defaultValue: 0.0,
    currentValue: 0.0,
    unit: 's',
  },
  P0145: {
    code: 'P0145',
    description: 'Frequência de Início da Frenagem CC',
    min: 0.0,
    max: 15.0,
    step: 0.1,
    defaultValue: 2.0,
    currentValue: 2.0,
    unit: 'Hz',
  },

  // ==========================================
  // GRUPO 3: MODOS DE CONTROLE (P0200 - P0229)
  // ==========================================
  P0202: {
    code: 'P0202',
    description: 'Tipo de Controle (0=V/F Escalar Linear, 1=V/F Quadrático, 2=Vetorial VVW)',
    min: 0,
    max: 2,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0204: {
    code: 'P0204',
    description: 'Carregar Configuração Padrão de Fábrica (5 = Reset Total)',
    min: 0,
    max: 5,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0205: {
    code: 'P0205',
    description: 'Parâmetro Inicial de Leitura do Display na Energização',
    min: 1,
    max: 9,
    step: 1,
    defaultValue: 2,
    currentValue: 2,
    unit: '',
  },
  P0206: {
    code: 'P0206',
    description: 'Função de Auto-Reset de Falhas (0=Desabilitado, 1=Habilitado)',
    min: 0,
    max: 1,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0208: {
    code: 'P0208',
    description: 'Tensão Nominal da Rede CA de Entrada',
    min: 200,
    max: 480,
    step: 10,
    defaultValue: 220,
    currentValue: 220,
    unit: 'V',
  },
  P0217: {
    code: 'P0217',
    description: 'Habilitação da Função Sleep / Dormir (Economia de Energia)',
    min: 0,
    max: 1,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0218: {
    code: 'P0218',
    description: 'Tempo de Inatividade para Acionar o Modo Sleep',
    min: 0,
    max: 999,
    step: 1,
    defaultValue: 120,
    currentValue: 120,
    unit: 's',
  },
  P0219: {
    code: 'P0219',
    description: 'Frequência de Despertar do Modo Sleep',
    min: 0.0,
    max: 300.0,
    step: 0.1,
    defaultValue: 10.0,
    currentValue: 10.0,
    unit: 'Hz',
  },
  P0220: {
    code: 'P0220',
    description: 'Origem da Seleção LOC/REM (0=Sempre LOC, 1=Sempre REM, 2=Tecla IHM, 3=DI)',
    min: 0,
    max: 3,
    step: 1,
    defaultValue: 2,
    currentValue: 2,
    unit: '',
  },
  P0221: {
    code: 'P0221',
    description: 'Fonte da Referência de Velocidade em Modo LOCAL (0=IHM, 1=AI1, 2=Modbus)',
    min: 0,
    max: 2,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0222: {
    code: 'P0222',
    description: 'Fonte de Referência de Velocidade em Modo REMOTO (0=IHM, 1=AI1, 6=Multispeed, 7=Modbus)',
    min: 0,
    max: 7,
    step: 1,
    defaultValue: 1,
    currentValue: 1,
    unit: '',
  },
  P0223: {
    code: 'P0223',
    description: 'Sentido de Giro em Modo LOCAL (0=Horário, 1=Anti-Horário, 2=Tecla IHM)',
    min: 0,
    max: 2,
    step: 1,
    defaultValue: 2,
    currentValue: 2,
    unit: '',
  },
  P0224: {
    code: 'P0224',
    description: 'Origem do Comando Gira/Para em Modo LOCAL (0=Teclas IHM, 1=Bornes DI)',
    min: 0,
    max: 1,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0225: {
    code: 'P0225',
    description: 'Comando JOG em Modo LOCAL (0=Inativo, 1=Teclas IHM, 2=DI)',
    min: 0,
    max: 2,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0226: {
    code: 'P0226',
    description: 'Sentido de Giro em Modo REMOTO (0=Horário, 1=Anti-Horário, 2=DI2/Bornes)',
    min: 0,
    max: 2,
    step: 1,
    defaultValue: 2,
    currentValue: 2,
    unit: '',
  },
  P0227: {
    code: 'P0227',
    description: 'Origem do Comando Gira/Para em Modo REMOTO (0=Teclas IHM, 1=Bornes DI1)',
    min: 0,
    max: 1,
    step: 1,
    defaultValue: 1,
    currentValue: 1,
    unit: '',
  },
  P0228: {
    code: 'P0228',
    description: 'Comando JOG em Modo REMOTO (0=Inativo, 1=Bornes DI)',
    min: 0,
    max: 1,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },

  // ==========================================
  // GRUPO 4: ENTRADAS & SAÍDAS (P0230 - P0299)
  // ==========================================
  P0231: {
    code: 'P0231',
    description: 'Função do Sinal da Entrada Analógica AI1 (0=Ref Frequência, 1=Ref Torque)',
    min: 0,
    max: 2,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0232: {
    code: 'P0232',
    description: 'Ganho da Entrada Analógica AI1',
    min: 0.0,
    max: 10.0,
    step: 0.01,
    defaultValue: 1.0,
    currentValue: 1.0,
    unit: '',
  },
  P0233: {
    code: 'P0233',
    description: 'Sinal da Entrada Analógica AI1 (0=0-10V, 1=4-20mA, 2=0-20mA)',
    min: 0,
    max: 2,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0234: {
    code: 'P0234',
    description: 'Offset / Deslocamento de Zero da Entrada AI1',
    min: -100.0,
    max: 100.0,
    step: 0.1,
    defaultValue: 0.0,
    currentValue: 0.0,
    unit: '%',
  },
  P0235: {
    code: 'P0235',
    description: 'Filtro da Entrada Analógica AI1',
    min: 0.0,
    max: 10.0,
    step: 0.01,
    defaultValue: 0.05,
    currentValue: 0.05,
    unit: 's',
  },
  P0251: {
    code: 'P0251',
    description: 'Função da Saída Analógica AO1 (0=Freq Saída, 1=Corrente, 2=RPM)',
    min: 0,
    max: 5,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0252: {
    code: 'P0252',
    description: 'Ganho da Saída Analógica AO1',
    min: 0.0,
    max: 10.0,
    step: 0.01,
    defaultValue: 1.0,
    currentValue: 1.0,
    unit: '',
  },
  P0253: {
    code: 'P0253',
    description: 'Tipo de Sinal da Saída AO1 (0=0-10V, 1=4-20mA, 2=0-20mA)',
    min: 0,
    max: 2,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0254: {
    code: 'P0254',
    description: 'Valor Máximo de Escala para Saída AO1',
    min: 0,
    max: 300,
    step: 1,
    defaultValue: 60,
    currentValue: 60,
    unit: 'Hz',
  },
  P0263: {
    code: 'P0263',
    description: 'Função da Entrada Digital DI1 (1=Gira/Para, 2=Habilita Geral)',
    min: 0,
    max: 20,
    step: 1,
    defaultValue: 1,
    currentValue: 1,
    unit: '',
  },
  P0264: {
    code: 'P0264',
    description: 'Função da Entrada Digital DI2 (1=Sentido de Giro, 2=Multispeed Bit 0)',
    min: 0,
    max: 20,
    step: 1,
    defaultValue: 1,
    currentValue: 1,
    unit: '',
  },
  P0265: {
    code: 'P0265',
    description: 'Função da Entrada Digital DI3 (1=Reset de Falhas, 2=Multispeed Bit 1)',
    min: 0,
    max: 20,
    step: 1,
    defaultValue: 2,
    currentValue: 2,
    unit: '',
  },
  P0266: {
    code: 'P0266',
    description: 'Função da Entrada Digital DI4 (1=JOG, 2=Multispeed Bit 2)',
    min: 0,
    max: 20,
    step: 1,
    defaultValue: 2,
    currentValue: 2,
    unit: '',
  },
  P0267: {
    code: 'P0267',
    description: 'Função da Entrada Digital DI5 (Opcional)',
    min: 0,
    max: 20,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0268: {
    code: 'P0268',
    description: 'Função da Entrada Digital DI6 (Opcional)',
    min: 0,
    max: 20,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0275: {
    code: 'P0275',
    description: 'Função da Saída a Relé RL1 (1=Motor Rodando / Run, 2=Pronto / Ready)',
    min: 0,
    max: 15,
    step: 1,
    defaultValue: 1,
    currentValue: 1,
    unit: '',
  },
  P0276: {
    code: 'P0276',
    description: 'Função da Saída a Relé RL2 (1=Inversor sem Falha / OK, 2=Com Falha)',
    min: 0,
    max: 15,
    step: 1,
    defaultValue: 2,
    currentValue: 2,
    unit: '',
  },
  P0277: {
    code: 'P0277',
    description: 'Função da Saída Digital a Transistor DO1',
    min: 0,
    max: 15,
    step: 1,
    defaultValue: 1,
    currentValue: 1,
    unit: '',
  },
  P0278: {
    code: 'P0278',
    description: 'Atraso na Energização do Relé RL1',
    min: 0.0,
    max: 99.9,
    step: 0.1,
    defaultValue: 0.0,
    currentValue: 0.0,
    unit: 's',
  },
  P0279: {
    code: 'P0279',
    description: 'Atraso na Desenergização do Relé RL1',
    min: 0.0,
    max: 99.9,
    step: 0.1,
    defaultValue: 0.0,
    currentValue: 0.0,
    unit: 's',
  },
  P0295: {
    code: 'P0295',
    description: 'Corrente Nominal do Inversor (Frame / Modelo CFW500)',
    min: 1.0,
    max: 50.0,
    step: 0.1,
    defaultValue: 7.0,
    currentValue: 7.0,
    unit: 'A',
    readOnly: true,
  },
  P0297: {
    code: 'P0297',
    description: 'Frequência de Chaveamento PWM Automática (Redução Térmica)',
    min: 0,
    max: 1,
    step: 1,
    defaultValue: 1,
    currentValue: 1,
    unit: '',
  },

  // ==========================================
  // GRUPO 5: COMUNICAÇÃO & IHM (P0300 - P0399)
  // ==========================================
  P0308: {
    code: 'P0308',
    description: 'Endereço Serial Modbus RTU RS-485 (Escravo)',
    min: 1,
    max: 247,
    step: 1,
    defaultValue: 1,
    currentValue: 1,
    unit: '',
  },
  P0310: {
    code: 'P0310',
    description: 'Taxa de Transmissão Serial / Baud Rate (0=9600, 1=19200, 2=38400, 3=57600)',
    min: 0,
    max: 3,
    step: 1,
    defaultValue: 1,
    currentValue: 1,
    unit: '',
  },
  P0311: {
    code: 'P0311',
    description: 'Configuração de Paridade Serial (0=Nenhum 1 Stop, 1=Par 1 Stop, 2=Ímpar 1 Stop)',
    min: 0,
    max: 2,
    step: 1,
    defaultValue: 1,
    currentValue: 1,
    unit: '',
  },
  P0312: {
    code: 'P0312',
    description: 'Protocolo de Comunicação (0=Modbus RTU, 1=CANopen, 2=Profibus)',
    min: 0,
    max: 2,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0313: {
    code: 'P0313',
    description: 'Ação em Caso de Falha de Comunicação Serial / Timeout (0=Desliga, 1=Mantém)',
    min: 0,
    max: 3,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0314: {
    code: 'P0314',
    description: 'Tempo Limite para Timeout Serial / Watchdog',
    min: 0.0,
    max: 99.9,
    step: 0.1,
    defaultValue: 1.0,
    currentValue: 1.0,
    unit: 's',
  },
  P0316: {
    code: 'P0316',
    description: 'Contador de Telegramas Seriais Modbus Válidos',
    min: 0,
    max: 65535,
    step: 1,
    defaultValue: 142,
    currentValue: 142,
    unit: '',
    readOnly: true,
  },
  P0340: {
    code: 'P0340',
    description: 'Habilitação da Tecla LOC/REM na IHM',
    min: 0,
    max: 1,
    step: 1,
    defaultValue: 1,
    currentValue: 1,
    unit: '',
  },
  P0341: {
    code: 'P0341',
    description: 'Habilitação da Tecla Gira/Sentido na IHM',
    min: 0,
    max: 1,
    step: 1,
    defaultValue: 1,
    currentValue: 1,
    unit: '',
  },

  // ==========================================
  // GRUPO 6: DADOS DO MOTOR (P0400 - P0409)
  // ==========================================
  P0400: {
    code: 'P0400',
    description: 'Tensão Nominal da Placa do Motor',
    min: 100,
    max: 500,
    step: 1,
    defaultValue: 220,
    currentValue: 220,
    unit: 'V',
  },
  P0401: {
    code: 'P0401',
    description: 'Frequência Nominal de Placa do Motor',
    min: 30.0,
    max: 300.0,
    step: 0.1,
    defaultValue: 60.0,
    currentValue: 60.0,
    unit: 'Hz',
  },
  P0402: {
    code: 'P0402',
    description: 'Rotação Nominal de Placa do Motor (RPM com Escorregamento)',
    min: 500,
    max: 18000,
    step: 1,
    defaultValue: 1750,
    currentValue: 1750,
    unit: 'rpm',
  },
  P0403: {
    code: 'P0403',
    description: 'Corrente Nominal de Placa do Motor',
    min: 0.1,
    max: 30.0,
    step: 0.1,
    defaultValue: 4.5,
    currentValue: 4.5,
    unit: 'A',
  },
  P0404: {
    code: 'P0404',
    description: 'Potência Nominal de Placa do Motor',
    min: 0.1,
    max: 20.0,
    step: 0.1,
    defaultValue: 1.5,
    currentValue: 1.5,
    unit: 'cv',
  },
  P0405: {
    code: 'P0405',
    description: 'Rendimento Nominal do Motor (Eta)',
    min: 50.0,
    max: 99.0,
    step: 0.1,
    defaultValue: 83.5,
    currentValue: 83.5,
    unit: '%',
  },
  P0406: {
    code: 'P0406',
    description: 'Fator de Potência Nominal do Motor (cos phi)',
    min: 0.5,
    max: 0.99,
    step: 0.01,
    defaultValue: 0.82,
    currentValue: 0.82,
    unit: '',
  },
  P0407: {
    code: 'P0407',
    description: 'Fator de Serviço do Motor (FS)',
    min: 1.0,
    max: 1.5,
    step: 0.01,
    defaultValue: 1.15,
    currentValue: 1.15,
    unit: '',
  },
  P0408: {
    code: 'P0408',
    description: 'Auto-Ajuste dos Parâmetros do Motor (0=Não, 1=Sim)',
    min: 0,
    max: 1,
    step: 1,
    defaultValue: 0,
    currentValue: 0,
    unit: '',
  },
  P0409: {
    code: 'P0409',
    description: 'Resistência Estatórica do Motor (Rs)',
    min: 0.0,
    max: 99.9,
    step: 0.1,
    defaultValue: 2.8,
    currentValue: 2.8,
    unit: 'Ω',
  },
};